import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { motion } from "framer-motion";
import { Award, CheckCircle2, ExternalLink, Loader2 } from "lucide-react";
import { getPublicPortfolioDocuments } from "../api/documentData";
import DocumentViewer from "./DocumentViewer";

const CERTIFICATES = [
  { fileName: "paklaring.pdf", titleId: "Surat Keterangan Pengalaman Kerja", titleEn: "Work Experience Certificate (Paklaring)", issuer: "PT Syahrendra Megawatt Indonesia", date: "05 Agustus 2026", descId: "Surat keterangan resmi pengalaman kerja sebagai Staf Administrasi dan Kontrol Dokumen, mengelola permohonan SLO/NIDI.", descEn: "Official work experience letter verifying role as Administration Staff managing SLO/NIDI data and document control.", tag: "Professional Experience" },
  { fileName: "KELULUSAN.pdf", titleId: "Surat Keterangan Kelulusan (SKL)", titleEn: "Certificate of Graduation", issuer: "SMA Negeri 1 Garut", date: "05 Mei 2023", descId: "Surat keterangan kelulusan jenjang SMA Jurusan MIPA dengan daftar nilai mata pelajaran yang sangat memuaskan.", descEn: "Official graduation document from MIPA (Science) major with excellent academic performance.", tag: "Education" },
  { fileName: "SERTIFIKAT.pdf", titleId: "Sertifikat Kompetensi Informatika", titleEn: "Informatics Competency Certificate", issuer: "SMA Negeri 1 Garut (Lab Komputer)", date: "08 Mei 2023", descId: "Sertifikat kompetensi mata pelajaran Informatika dengan fokus Integrasi Office, Analisis Data, dan Algoritma Pemrograman.", descEn: "Competency certificate focusing on Office Integration, Data Analysis, Computer Networks, and Programming.", tag: "Technical Skill" },
  { fileName: "PIAGAN PENGHARGAAN.pdf", titleId: "Piagam Penghargaan Karya Tulis Ilmiah", titleEn: "Scientific Paper Award", issuer: "SMA Negeri 1 Garut", date: "03 Februari 2023", descId: "Meraih predikat Sangat Memuaskan dengan nilai 86 untuk Uji Karya Tulis Ilmiah tentang Pengaruh Game Online Terhadap Sikap Belajar.", descEn: "Awarded 'Sangat Memuaskan' (Score: 86) for scientific research paper titled 'Pengaruh Game Online Terhadap Sikap Belajar'.", tag: "Achievement" },
];

export default function ProtectedCertificates() {
  const { i18n } = useTranslation();
  const isEn = i18n.language === "en";
  const [documents, setDocuments] = useState([]);
  const [selected, setSelected] = useState(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; getPublicPortfolioDocuments().then(({ data }) => { if (active) { setDocuments(data); setLoading(false); } }); return () => { active = false; }; }, []);
  return <section id="certificates" style={{ padding: "80px 20px" }}><div style={{ maxWidth: "1000px", margin: "0 auto" }}>
    <motion.h2 initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} style={{ fontSize: "2rem", fontWeight: "800", color: "var(--text-primary)", marginBottom: "40px" }}>{isEn ? "Certificates & Credentials" : "Sertifikat & Kredensial"} <span style={{ color: "var(--accent)" }}>.</span></motion.h2>
    {loading && <div style={{ color: "var(--text-secondary)", display: "flex", gap: 8, alignItems: "center" }}><Loader2 className="animate-spin" size={18} />{isEn ? "Loading documents…" : "Memuat dokumen…"}</div>}
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: "24px" }}>{CERTIFICATES.map((item, idx) => { const document = documents.find((entry) => entry.file_name === item.fileName); return <motion.div key={item.fileName} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: idx * 0.1 }} className="glass-card" style={{ padding: "28px", display: "flex", flexDirection: "column", justifyContent: "space-between" }}><div><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "16px" }}><div style={{ padding: "10px", backgroundColor: "rgba(59, 130, 246, 0.12)", borderRadius: "12px", display: "flex", color: "var(--accent)" }}><Award size={22} /></div><span className="tech-pill">{item.tag}</span></div><h3 style={{ fontSize: "1.15rem", fontWeight: "700", color: "var(--text-primary)", marginBottom: "6px" }}>{isEn ? item.titleEn : item.titleId}</h3><p style={{ color: "var(--accent)", fontWeight: "600", fontSize: "0.9rem", marginBottom: "10px" }}>{item.issuer} • <span style={{ color: "var(--text-secondary)", fontSize: "0.85rem" }}>{item.date}</span></p><p style={{ color: "var(--text-secondary)", fontSize: "0.93rem", lineHeight: "1.6", marginBottom: "20px" }}>{isEn ? item.descEn : item.descId}</p></div><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingTop: "16px", borderTop: "1px solid var(--card-border)" }}><div style={{ display: "flex", alignItems: "center", gap: "6px", color: "#10B981", fontSize: "0.82rem", fontWeight: "600" }}><CheckCircle2 size={16} /><span>Verified</span></div>{document && <button type="button" onClick={() => setSelected(document)} style={{ display: "inline-flex", alignItems: "center", gap: "6px", color: "var(--accent)", fontSize: "0.85rem", fontWeight: "700", backgroundColor: "rgba(34, 211, 238, 0.1)", padding: "6px 12px", borderRadius: "10px", border: "1px solid rgba(34, 211, 238, 0.25)", cursor: "pointer" }}><span>{isEn ? "View document" : "Lihat Dokumen"}</span><ExternalLink size={14} /></button>}</div></motion.div>; })}</div>
  </div>{selected && <DocumentViewer document={selected} isEn={isEn} onClose={() => setSelected(null)} />}</section>;
}
